import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import Nav from "./_components/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InsightLoom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  );
}
